services:
  frontend:
    image: "nginx:alpine"
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/home/node/app

  db:
    image: "postgres:14-alpine"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ds